package Daje;
use Mojo::Base 'Mojolicious', -signatures;

# NAME
# ====
#
# Daje - is a Mojolicious server serveing Daje stuff
#
#
#
# SYNOPSIS
# ========
#
#    use Daje;
#
# DESCRIPTION
# ===========
#
# Daje is a web server
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#

use Daje::Tools::JWT;
use Mojo::Pg;

our $VERSION = "0.04";

# This method will run once at server start
sub startup ($self) {

  # Load configuration from config file
  my $config = $self->plugin('Config');
  $self->log->path($self->config('log'));
  $self->log->level($self->config('loglevel'));

  $self->helper(pg => sub {state $pg = Mojo::Pg->new->dsn(shift->config('pg'))});

  #$self->helper(jwt => sub {state $jwt = Daje::Tools::JWT->new()});
  $self->plugin('Daje::Plugin::Apploader');
  # Configure the application
  $self->secrets($config->{secrets});

  #push @{$self->plugins->namespaces}, 'Daje::Plugin';
  #push @{$self->routes->namespaces}, 'Daje::Controller';

  #$self->plugin('Workflow');
  #$self->plugin('Login');

  # Router
  #my $r = $self->routes;

  # Normal route to controller

  #$r->put('/api/signup/')->to('Signup#signup');
}

1;

#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje - is a Mojolicious server serveing Daje stuff





=head1 SYNOPSIS


   use Daje;



=head1 DESCRIPTION


Daje is a web server




=head1 REQUIRES

L<Mojo::Base> 


=head1 METHODS

=head2 startup

 startup();

This method will run once at server start



=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

